import geoalchemy2

"""create_secure_personal_data_vault

Revision ID: fb0ddd0c8aea
Revises: c209c1826454
Create Date: 2026-06-08 15:14:33.524247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0ddd0c8aea'
down_revision: Union[str, Sequence[str], None] = 'c209c1826454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secure_personal_data_vault',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('association_token', sa.String(), nullable=False),
    sa.Column('encrypted_farmer_name', sa.String(), nullable=False),
    sa.Column('encrypted_nib', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secure_personal_data_vault_association_token'), 'secure_personal_data_vault', ['association_token'], unique=True)
    op.alter_column('audit_ledger', 'payload_json',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('hgu_prioritas_1_nomor_sertifikat_key'), 'hgu_prioritas_1', type_='unique')
    op.drop_index(op.f('idx_hgu_geom'), table_name='hgu_prioritas_1', postgresql_using='gist')
    op.create_index('idx_hgu_prioritas_1_geom', 'hgu_prioritas_1', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_hgu_prioritas_1_nomor_sertifikat'), 'hgu_prioritas_1', ['nomor_sertifikat'], unique=True)
    op.drop_index(op.f('idx_hutan_geom'), table_name='kawasan_hutan_prioritas_3', postgresql_using='gist')
    op.create_index('idx_kawasan_hutan_prioritas_3_geom', 'kawasan_hutan_prioritas_3', ['geom'], unique=False, postgresql_using='gist')
    op.drop_constraint(op.f('plots_plot_id_key'), 'plots', type_='unique')
    op.create_index(op.f('ix_plots_plot_id'), 'plots', ['plot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plots_plot_id'), table_name='plots')
    op.create_unique_constraint(op.f('plots_plot_id_key'), 'plots', ['plot_id'])
    op.drop_index('idx_kawasan_hutan_prioritas_3_geom', table_name='kawasan_hutan_prioritas_3', postgresql_using='gist')
    op.create_index(op.f('idx_hutan_geom'), 'kawasan_hutan_prioritas_3', ['geom'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_hgu_prioritas_1_nomor_sertifikat'), table_name='hgu_prioritas_1')
    op.drop_index('idx_hgu_prioritas_1_geom', table_name='hgu_prioritas_1', postgresql_using='gist')
    op.create_index(op.f('idx_hgu_geom'), 'hgu_prioritas_1', ['geom'], unique=False, postgresql_using='gist')
    op.create_unique_constraint(op.f('hgu_prioritas_1_nomor_sertifikat_key'), 'hgu_prioritas_1', ['nomor_sertifikat'])
    op.alter_column('audit_ledger', 'payload_json',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_secure_personal_data_vault_association_token'), table_name='secure_personal_data_vault')
    op.drop_table('secure_personal_data_vault')
    # ### end Alembic commands ###
